### ISSUE TITLE
Issue with Network Error During Login, Registration, or forgot password.

### ISSUE THREAD

**Issue by adhityadogra** [Jumanjigobez/HomeSys#2]
I have followed the installation steps provided on your page. The site loads correctly up to the login page, but I am encountering a "network error" message whenever I attempt to log in, register, or use the "forgot password" option. I checked the network terminal   from browser inspect adn found out that server is refusing to connect

<img width="960" alt="error" src="https://github.com/user-attachments/assets/c993f282-80b1-417c-9c5e-309bf0649bcb">

Due to this issue, I am unable to proceed further into the site. I initially thought this might be a problem on my end, so I had a few classmates test it as well, but they experienced the same issue.

There might be some missing steps in the installation guide or there might be a bug. Please provide a solution for this at the earliest.

**Comment by Jumanjigobez** [comment]
Hey @adhityadogra,

Thank you for trying out HomeSys! To resolve the issue you encountered, please follow the below different approaches:

1. **Check Your Apache PHP Server**: 
   - Ensure your Apache PHP server is running on port **8080**. 
   - If you need help changing the port in XAMPP, you can refer to [this YouTube tutorial](https://youtu.be/pugSKPdX0u8?si=A9kr9LCp2eMfJhK3) for instructions.

2. **Update `routes.js`**:
   - Open the `routes.js` file located in the `src` folder.
   - Find line **30**, which should contain:
     ```javascript
     export const api_url = "http://localhost:8080/HOMESYS V1.0/homesys/PHP";
     ```
   - You can either remove the port to use:
     ```javascript
     export const api_url = "http://localhost/HOMESYS V1.0/homesys/PHP";
     ```
     or specify the port your Apache server is using.

If you need further assistance, feel free to reply!

**Comment by adhityadogra** [comment]
I have changed the ports using the yt link you provided but it still hasnt resolved the issue.
but still the issue persists only this time its showing different error in network console.

<img width="710" alt="Screenshot 2024-09-29 200537" src="https://github.com/user-attachments/assets/f14d2c60-834e-49c7-a611-be3850ae43d6">
<img width="497" alt="Screenshot 2024-09-29 200506" src="https://github.com/user-attachments/assets/c7091841-b5e5-4df5-aec4-c832476d419e">
<img width="960" alt="error2" src="https://github.com/user-attachments/assets/5582ffae-074e-42b6-a551-700706d5ca15">

**Comment by Jumanjigobez** [comment]
Issue Fixed, the problem was directory file tree structure.
The folder `HOMESYS V1.0` was not found.

Thanks Again :)
